language: python
python:
- "3.5"
before_install:
  - "pip install -U pip"
  - "python setup.py install"
script:
- python -m unittest discover -v -s ./test/ -p '*.py'
- python -m unittest discover -v -s ./oefeningen/ -p '*.py'
